# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
use = ""

# : }}}

# : Manager {{{

[mgr]
cwd = { fg = "cyan" }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "blue" }

# Border
border_symbol = " "
border_style  = { fg = "gray" }

# Highlighting
syntect_theme = ""

# : }}}

# : Manager {{{

[indicator]
# Hovered
current = { reversed = true }
preview = { underline = true }

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "gray", bg = "gray" }

# Mode
mode_normal = { bg = "blue", bold = true }
mode_select = { bg = "red", bold = true }
mode_unset  = { bg = "red", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }

# : }}}


# : Select {{{

[select]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on      = { fg = "cyan" }
run     = { fg = "magenta" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "cyan" },

	# Media
	{ mime = "{audio,video}/*", fg = "yellow" },

	# Archives
	{ mime = "application/*zip", fg = "magenta" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "magenta" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "green" },

	# Fallback
	# { url = "*", fg = "white" },
	{ url = "*/", fg = "blue" }
]

[icon]

rules = [
	# Programming
	{ url = "*.c"    , text = "", fg = "#599eff" },
	{ url = "*.cpp"  , text = "", fg = "#519aba" },
	{ url = "*.class", text = "", fg = "#cc3e44" },
	{ url = "*.cs"   , text = "󰌛", fg = "#596706" },
	{ url = "*.css"  , text = "", fg = "#42a5f5" },
	{ url = "*.elm"  , text = "", fg = "#4391d2" },
	{ url = "*.fish" , text = "", fg = "#4d5a5e" },
	{ url = "*.go"   , text = "", fg = "#519aba" },
	{ url = "*.h"    , text = "", fg = "#a074c4" },
	{ url = "*.hpp"  , text = "", fg = "#a074c4" },
	{ url = "*.html" , text = "", fg = "#e44d26" },
	{ url = "*.jar"  , text = "", fg = "#cc3e44" },
	{ url = "*.java" , text = "", fg = "#cc3e44" },
	{ url = "*.js"   , text = "", fg = "#F1F134" },
	{ url = "*.jsx"  , text = "", fg = "#20c2e3" },
	{ url = "*.lua"  , text = "", fg = "#51a0cf" },
	{ url = "*.nix"  , text = "", fg = "#7ebae4" },
	{ url = "*.nu"   , text = ">", fg = "#3aa675" },
	{ url = "*.php"  , text = "", fg = "#a074c4" },
	{ url = "*.py"   , text = "", fg = "#ffbc03" },
	{ url = "*.rb"   , text = "", fg = "#701516" },
	{ url = "*.rs"   , text = "", fg = "#dea584" },
	{ url = "*.sbt"  , text = "", fg = "#4d5a5e" },
	{ url = "*.scala", text = "", fg = "#cc463e" },
	{ url = "*.scss" , text = "", fg = "#f55385" },
	{ url = "*.sh"   , text = "", fg = "#4d5a5e" },
	{ url = "*.swift", text = "", fg = "#e37933" },
	{ url = "*.ts"   , text = "", fg = "#519aba" },
	{ url = "*.tsx"  , text = "", fg = "#1354bf" },
	{ url = "*.vim"  , text = "", fg = "#019833" },
	{ url = "*.vue"  , text = "󰡄", fg = "#8dc149" },

	# Text
	{ url = "*.conf", text = "", fg = "#6d8086" },
	{ url = "*.ini" , text = "", fg = "#6d8086" },
	{ url = "*.json", text = "", fg = "#cbcb41" },
	{ url = "*.kdl" , text = "", fg = "#6d8086" },
	{ url = "*.md"  , text = "", fg = "#ffffff" },
	{ url = "*.toml", text = "", fg = "#ffffff" },
	{ url = "*.txt" , text = "", fg = "#89e051" },
	{ url = "*.yaml", text = "", fg = "#6d8086" },
	{ url = "*.yml" , text = "", fg = "#6d8086" },

	# Archives
	{ url = "*.7z" , text = "" },
	{ url = "*.bz2", text = "" },
	{ url = "*.gz" , text = "" },
	{ url = "*.rar", text = "" },
	{ url = "*.tar", text = "" },
	{ url = "*.xz" , text = "" },
	{ url = "*.zip", text = "" },

	# Images
	{ url = "*.HEIC", text = "", fg = "#a074c4" },
	{ url = "*.avif", text = "", fg = "#a074c4" },
	{ url = "*.bmp" , text = "", fg = "#a074c4" },
	{ url = "*.gif" , text = "", fg = "#a074c4" },
	{ url = "*.ico" , text = "", fg = "#cbcb41" },
	{ url = "*.jpeg", text = "", fg = "#a074c4" },
	{ url = "*.jpg" , text = "", fg = "#a074c4" },
	{ url = "*.png" , text = "", fg = "#a074c4" },
	{ url = "*.svg" , text = "", fg = "#FFB13B" },
	{ url = "*.webp", text = "", fg = "#a074c4" },

	# Movies
	{ url = "*.avi" , text = "", fg = "#FD971F" },
	{ url = "*.mkv" , text = "", fg = "#FD971F" },
	{ url = "*.mov" , text = "", fg = "#FD971F" },
	{ url = "*.mp4" , text = "", fg = "#FD971F" },
	{ url = "*.webm", text = "", fg = "#FD971F" },

	# Audio
	{ url = "*.aac" , text = "", fg = "#66D8EF" },
	{ url = "*.flac", text = "", fg = "#66D8EF" },
	{ url = "*.m4a" , text = "", fg = "#66D8EF" },
	{ url = "*.mp3" , text = "", fg = "#66D8EF" },
	{ url = "*.ogg" , text = "", fg = "#66D8EF" },
	{ url = "*.wav" , text = "", fg = "#66D8EF" },

	# Documents
	{ url = "*.csv" , text = "", fg = "#89e051" },
	{ url = "*.doc" , text = "", fg = "#185abd" },
	{ url = "*.doct", text = "", fg = "#185abd" },
	{ url = "*.docx", text = "", fg = "#185abd" },
	{ url = "*.dot" , text = "", fg = "#185abd" },
	{ url = "*.ods" , text = "", fg = "#207245" },
	{ url = "*.ots" , text = "", fg = "#207245" },
	{ url = "*.pdf" , text = "", fg = "#b30b00" },
	{ url = "*.pom" , text = "", fg = "#cc3e44" },
	{ url = "*.pot" , text = "", fg = "#cb4a32" },
	{ url = "*.potx", text = "", fg = "#cb4a32" },
	{ url = "*.ppm" , text = "", fg = "#a074c4" },
	{ url = "*.ppmx", text = "", fg = "#cb4a32" },
	{ url = "*.pps" , text = "", fg = "#cb4a32" },
	{ url = "*.ppsx", text = "", fg = "#cb4a32" },
	{ url = "*.ppt" , text = "", fg = "#cb4a32" },
	{ url = "*.pptx", text = "", fg = "#cb4a32" },
	{ url = "*.xlc" , text = "", fg = "#207245" },
	{ url = "*.xlm" , text = "", fg = "#207245" },
	{ url = "*.xls" , text = "", fg = "#207245" },
	{ url = "*.xlsm", text = "", fg = "#207245" },
	{ url = "*.xlsx", text = "", fg = "#207245" },
	{ url = "*.xlt" , text = "", fg = "#207245" },

	# Lockfiles
	{ url = "*.lock", text = "", fg = "#bbbbbb" },

	# Misc
	{ url = "*.bin", text = "", fg = "#9F0500" },
	{ url = "*.exe", text = "", fg = "#9F0500" },
	{ url = "*.pkg", text = "", fg = "#9F0500" },

	# Dotfiles
	{ url = ".DS_Store"     , text = "", fg = "#41535b" },
	{ url = ".bashprofile"  , text = "", fg = "#89e051" },
	{ url = ".bashrc"       , text = "", fg = "#89e051" },
	{ url = ".gitattributes", text = "", fg = "#41535b" },
	{ url = ".gitignore"    , text = "", fg = "#41535b" },
	{ url = ".gitmodules"   , text = "", fg = "#41535b" },
	{ url = ".vimrc"        , text = "", fg = "#019833" },
	{ url = ".zprofile"     , text = "", fg = "#89e051" },
	{ url = ".zshenv"       , text = "", fg = "#89e051" },
	{ url = ".zshrc"        , text = "", fg = "#89e051" },

	# Named files
	{ url = "COPYING"      , text = "󰿃", fg = "#cbcb41" },
	{ url = "Containerfile", text = "󰡨", fg = "#458ee6" },
	{ url = "Dockerfile"   , text = "󰡨", fg = "#458ee6" },
	{ url = "LICENSE"      , text = "󰿃", fg = "#d0bf41" },

	# Directories
	{ url = ".config/"    , text = "" },
	{ url = ".git/"       , text = "" },
	{ url = "Desktop/"    , text = "" },
	{ url = "Development/", text = "" },
	{ url = "Documents/"  , text = "" },
	{ url = "Downloads/"  , text = "" },
	{ url = "Library/"    , text = "" },
	{ url = "Movies/"     , text = "" },
	{ url = "Music/"      , text = "" },
	{ url = "Pictures/"   , text = "" },
	{ url = "Public/"     , text = "" },
	{ url = "Videos/"     , text = "" },

	# Default
	{ url = "*" , text = "" },
	{ url = "*/", text = "" },
]

# : }}}
